### ISSUE TITLE
Conda IOError when installing any package

### ISSUE THREAD

**Issue by GlenHertz** [Luthaf/Conda.jl#27]
(Perhaps this is an upstream issue but I'm not sure.)

I was trying to install IJulia after moving my `~/.julia/v0.4` directory out of the way and it errorred out when Conda was trying to install some packages.  In trying to narrow down the issue, if I run conda from the command line `/u/hertz/.julia/v0.4/Conda/deps/usr/bin/conda install -y pip` its output is:

```
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /u/hertz/.julia/v0.4/Conda/deps/usr:

The following NEW packages will be INSTALLED:

    pip:        7.1.2-py27_0 
    setuptools: 18.8.1-py27_0
    wheel:      0.26.0-py27_1

The following packages will be UPDATED:

    conda:      3.9.1-py27_0 --> 3.18.9-py27_0
    conda-env:  2.1.3-py27_0 --> 2.4.5-py27_0 
    openssl:    1.0.1k-0     --> 1.0.2d-0     
    python:     2.7.9-1      --> 2.7.11-0     
    pyyaml:     3.11-py27_0  --> 3.11-py27_1  
    requests:   2.5.3-py27_0 --> 2.9.0-py27_0 
    sqlite:     3.8.4.1-0    --> 3.8.4.1-1    
    tk:         8.5.15-0     --> 8.5.18-0     
    yaml:       0.1.4-0      --> 0.1.6-0      

Extracting packages ...
An unexpected error has occurred, please consider sending the                                                                              |  12%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/instructions.py", line 55, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/conda/install.py", line 448, in extract
    t.extractall(path=path)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/tarfile.py", line 2070, in extractall
    self.extract(tarinfo, path)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/tarfile.py", line 2107, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/tarfile.py", line 2183, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/u/hertz/.julia/v0.4/Conda/deps/usr/lib/python2.7/tarfile.py", line 2224, in makefile
    copyfileobj(source, target)
IOError: [Errno 5] Input/output error
```

Also, `/u/hertz/.julia/v0.4/Conda/deps/usr/bin/conda info` returns:

```
Current conda install:

             platform : linux-64
        conda version : 3.9.1
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /u/hertz/.julia/v0.4/Conda/deps/usr  (writable)
  default environment : /u/hertz/.julia/v0.4/Conda/deps/usr
     envs directories : /u/hertz/.julia/v0.4/Conda/deps/usr/envs
        package cache : /u/hertz/.julia/v0.4/Conda/deps/usr/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

`versioninfo()` reports:

```
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
  WORD_SIZE: 64
           "Red Hat Enterprise Linux Workstation release 6.4 (Santiago)"
  uname: Linux 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64
Memory: 504.78792572021484 GB (508220.28515625 MB free)
Uptime: 733885.0 sec
Load Avg:  0.35791015625  0.16845703125  0.11279296875
Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz: 
          speed         user         nice          sys         idle          irq
#1-20  2992 MHz   58099163 s         20 s    3562866 s  1404979894 s        127 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Package Directory: /u/hertz/.julia/v0.4
2 required packages:
 - Compat                        0.7.8
 - IJulia                        1.1.8
7 additional packages:
 - BinDeps                       0.3.20
 - Conda                         0.1.8
 - JSON                          0.5.0
 - Nettle                        0.2.0
 - SHA                           0.1.2
 - URIParser                     0.1.1
 - ZMQ                           0.3.1
```

If this is an upstream issue or if there is anything I can try please let me know.

**Comment by Luthaf** [comment]
> IOError: [Errno 5] Input/output error

This error number is for [generic I/O error](http://www.virtsync.com/c-error-codes-include-errno). So this could be something with your home directory/hard drive. Does this error persist with another user?

You can also try to `rm -rf /u/hertz/.julia/v0.4/Conda` and then add the `Conda.jl` package again.

**Comment by Luthaf** [comment]
You can also try to install the new conda package one at the time to check which one is failling. Specifically, runing `/u/hertz/.julia/v0.4/Conda/deps/usr/bin/conda install --no-deps requests`, `/u/hertz/.julia/v0.4/Conda/deps/usr/bin/conda install --no-deps conda`, ...

**Comment by GlenHertz** [comment]
Thanks.  I was out of space on the disk and removing some files fixed the issue.
